env:
  browser: true
  es2020: true
extends:
  - standard
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules: 
  prettier/prettier: error
