env:
  browser: true
  es2020: true
  jest/globals: true
extends:
  - standard
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - jest
rules:
  prettier/prettier: error
